services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ingestor:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://news_user:news_pass@db:5432/newsdb
      SCHEDULE_CRON: "*/15 * * * *"
      TZ: Europe/Istanbul
      LOG_LEVEL: INFO
    depends_on:
      - db

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://news_user:news_pass@db:5432/newsdb
      TZ: Europe/Istanbul
      LOG_LEVEL: INFO
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:
